### PR TITLE
Add router + Navbar improvements

### LINKED ISSUE #56: [UX] Improve UX with Navbar
Currently when user is on 'PIXABAY' Gallery page and refreshes the page, app will display 'GIPHY' page as default. 
It would be nice to stay in the same page when user refreshes.

### PR DESCRIPTION
**Pull request by furkanmutlu**
## Fixes Issue

Closes #56 

## Changes proposed

- Inroduced react router v6
- Improvements on Navbar UI/UX
- Improvements on constant variables

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by AlfiyaSiddique — COMMENTED** [review]
Hello @furkanmutlu

On deploy-preview when I refresh the page, It isn't working as expected.  On refreshing, the following error appears

Screenshot 2022-12-31 205827

Not sure about the reason for this error, but
Inside the src/router/index.js file, the Router component has the prop **path = {apiType}**, 
try with a  slash before the apiType, so the resultant value assigned to this prop is **/{apiType}**

**Comment by furkanmutlu** [comment]
> Not sure about the reason for this error, but Inside the src/router/index.js file, the Router component has the prop **path = {apiType}**, try with a slash before the apiType, so the resultant value assigned to this prop is **/{apiType}**

hmm just pushed this. It didnt seem to fix the issue. It is working on local env tho. It is an interesting issue.

**Comment by furkanmutlu** [comment]
I think I found the issue and the solution here: https://www.freecodecamp.org/news/how-to-deploy-react-router-based-app-to-netlify/#:~:text=This%20is%20because,to%20fix%20this.

**Comment by furkanmutlu** [comment]
@AlfiyaSiddique fixed the netlify deploy preview issue. Should be working now.

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique I think I found the issue and the solution here: https://www.freecodecamp.org/news/how-to-deploy-react-router-based-app-to-netlify/#:~:text=This%20is%20because,to%20fix%20this.
Great! It's working perfectly👍🏻

**Review by elyessAR — APPROVED** [review]

**Review by AlfiyaSiddique — APPROVED** [review]

**Pull request merged**
